---
apiVersion: v1
kind: Service
metadata:
  name: flappy-bird-lb
spec:
  type: LoadBalancer
  ports:
  - name: frontend
    port: 80
    targetPort: 3000
  - name: ws
    port: 3001
    targetPort: 3001
  selector:
      app: flappy-bird
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flappy-bird-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flappy-bird
  template:
    metadata:
      labels:
        app: flappy-bird
    spec:
      containers:
      - name: flappy-bird
        image: juanma1223/flappy-bird-sd:0.69
        # ports:
        # - containerPort: 3000
